services:
  app:
    entrypoint: ["./docker/app/entrypoint.sh"]
    container_name: app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  web:
    image: nginx
    container_name: web
    ports:
      - "80:80"
      - "5173:5173"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql
    container_name: db
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db:/var/lib/mysql

networks:
  default:
    driver: bridge



